spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:13306/sampledb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #username: lacm
    #password: lacm123
    url: ${E2E-COMMAND_DATASOURCE_URL}
    username: ${E2E-COMMAND_DATASOURCE_USERNAME}
    password: ${SECRET_E2E-COMMAND_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      # maximum-pool-size: ${E2E-COMMAND_DATASOURCE_POOL_MAX_SIZE}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      cache:
        use_second_level_cache: false
        use_query_cache: false
      properties:
        hibernate:
          generate_statistics: true
          
jpa:
  # database-platform: org.hibernate.dialect.Oracle12cDialect
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    # dialect: org.hibernate.dialect.Oracle12cDialect
    dialect: org.hibernate.dialect.MySQL8Dialect
    ddl-auto: create
    show-sql: true
    cache:
      use_second_level_cache: false
      use_query_cache: false
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
      base-path: /metrics
  endpoint:
    health:
      probes:
        enabled: true
opentracing:
  jaeger:
    enable-128-bit-traces: true
    enable-b3-propagation: true
    service-name: command.gint-ps-poc
logging:
  level:
    root: ERROR
    org.springframework: INFO
    org.hibernate: INFO
    es.seg_social: DEBUG
springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
